name: TikTok_Auto_Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install playwright playwright-stealth httpx opencv-python-headless numpy

      - name: Instalar Navegador
        run: |
          python -m playwright install chromium
          python -m playwright install-deps chromium

      - name: Ejecutar Script
        run: python bot.py

      - name: Descargar Cuentas
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cuentas_tiktok
          path: cuentas.txt
